---
# config/backtest_ktw.yaml
# 回测KeyTimeWeightTurningPointStrategy策略的配置文件

backtest:
  strategy_name: KeyTimeWeightTurningPointStrategy
  strategy_params:
    KeyTimeWeightTurningPointStrategy:
      ktwtp_params:
        key_time_hours_after_event: [1, 3, 5]
        use_space_boundaries_as_turning_points: true
        turning_point_buffer_pips: 10
        confirm_with_m5_m15: false
        m5_m15_lookback: 6
        stop_loss_buffer_pips: 15
        take_profit_target: 'opposite_boundary'
        risk_reward_ratio: 1.5
        # 新增Node和Natural Retracement参数
        use_natural_retracement_tp: true
        natural_retracement_levels: [0.382, 0.5, 0.618]
        use_node_tp: true
        node_proximity_buffer_pips: 5
      event_mapping:
        currency_to_symbol:
          USD: EURUSD
          EUR: EURUSD
          GBP: GBPUSD
        default_event_symbol: EURUSD
      primary_timeframe: "M30"

  # 引擎配置
  engine:
    # 回测时间范围
    start_date: "2024-10-01"
    end_date: "2024-10-03"
    symbols: ["EURUSD", "GBPUSD"]
    primary_timeframe: "M30"
    # 策略模块路径
    strategy_module_path: "strategies.key_time_weight_turning_point_strategy"
  
  # 初始资金
  cash: 100000

# 结果分析器参数
analyzer:
  # 风险设置
  risk_free_rate: 0.02
  # 图表输出设置
  plot_results: true
  plot_save_path: "output/backtest_plots"
  # 报告输出设置
  report_save_path: "output/backtest_reports"
  report_format: "html"

# 经济日历数据库路径
economic_calendar:
  paths:
    database_file: "data/calendar/filtered/history/economic_calendar.db"

# 执行引擎特定配置
execution_engine:
  sandbox:
    commission_per_trade: 1.5

# 风险管理器配置
risk_manager:
  type: "NewFixedFractional"
  params:
    risk_per_trade_percentage: "0.05"
    default_contract_size: "100000"
    min_volume: "0.01"
    volume_precision: 2

space_definition:
  forward_bars: 6
  boundary_percentile: 90
  min_space_pips: 20

# 事件货币到交易品种的映射
event_mapping:
  currency_to_symbol:
    USD: EURUSD
    EUR: EURUSD
    GBP: GBPUSD
    JPY: USDJPY
    AUD: AUDUSD
    CAD: USDCAD
    NZD: NZDUSD
    CHF: USDCHF

# 日志配置
logging:
  backtest_log_filename: "backtest_ktw.log"
  log_dir: "logs"
  level: "INFO"
  console_level: "INFO"

# 数据提供者配置
data_provider:
  type: "MarketDataProvider"
  data_padding_days: 0