---
# live_trading/config/live_config.yaml
# 实盘交易配置文件

# 策略配置
strategy:
  name: KeyTimeWeightTurningPointStrategy
  params:
    KeyTimeWeightTurningPointStrategy:
      ktwtp_params:
        key_time_hours_after_event: [1, 3, 5, 8, 12, 18, 24, 36, 48]
        use_space_boundaries_as_turning_points: true
        turning_point_buffer_pips: 10
        confirm_with_m5_m15: false
        m5_m15_lookback: 6
        stop_loss_buffer_pips: 15
        take_profit_target: 'opposite_boundary'
        risk_reward_ratio: 1.5
      event_mapping:
        currency_to_symbol:
          USD: EURUSD
          EUR: EURUSD
          GBP: GBPUSD
          JPY: USDJPY
          AUD: AUDUSD
          CAD: USDCAD
          NZD: NZDUSD
          CHF: USDCHF
          CNY: USDCNH
        default_event_symbol: EURUSD
      primary_timeframe: "M30"

    ExhaustionStrategy:
      primary_timeframe: "M30"

# 执行引擎配置
execution_engine:
  type: "live"
  broker: "MT5" # 或 "cTrader" 等
  server: "Demo" # 或 "Real"
  account: 123456
  password: "" # 建议通过环境变量设置
  symbol_prefix: "" # 经纪商特定的符号前缀
  symbol_suffix: "" # 经纪商特定的符号后缀
  
  # 实盘特有配置
  live_params:
    max_slippage_pips: 2
    requote_timeout_ms: 3000
    partial_fills: false
    
  # 佣金设置
  commission_per_trade: 1.5

# 风险管理配置
risk_manager:
  type: "NewFixedFractional"
  params:
    risk_per_trade_percentage: "0.05"
    default_contract_size: "100000"
    min_volume: "0.01"
    volume_precision: 2

# 空间定义参数
space_definition:
  forward_bars: 6
  boundary_percentile: 90
  min_space_pips: 20

# 经济日历配置
economic_calendar:
  paths:
    database_file: "data/calendar/filtered/history/economic_calendar.db"
  update_frequency: "daily"
  timezone: "UTC"

# 日志和监控
monitoring:
  telegram_alerts: false
  email_alerts: false
  log_level: "INFO"
  log_file: "logs/live_trading.log"

# 初始资金
account:
  initial_balance: 100000
  currency: "USD"
  leverage: 100

# 数据订阅
data_subscriptions:
  symbols:
    - "EURUSD"
    - "GBPUSD"
    - "USDJPY"
    - "AUDUSD"
    - "USDCAD"
    - "NZDUSD"
    - "USDCHF"
    - "USDCNH"
  timeframes:
    - "M30"
    - "H1"
    - "H4"
    - "D1"